/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Site Configuration Content
 * This file contains all customizable values for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Brand: Tiny Tested
 * Generated: 2025-12-29T17:21:37.536Z
 */

import type { SiteConfigSchema, ColorConfigSchema } from './config.schema'

/**
 * Main site configuration
 * Values auto-populated from brand database
 */
export const siteContent: SiteConfigSchema = {
  // Brand identity
  brand: {
    id: "f28898d7-1d45-4d02-b777-c7411281c441",
    name: "Tiny Tested",
    description: "TinyTrend Insights delivers expert-driven, meticulously tested reviews and comparisons of essential baby products to empower informed parenting choices.",
    url: "https://tinytested.blog",
    logoPath: "/logo.jpg",
    faviconPath: "/logo.jpg",
    ogImagePath: "/logo.jpg",
    mainAppUrl: "https://app.thefaceless.ai",
    legalEmail: "support@banedigital.com",
    privacyEmail: "support@banedigital.com",
    tagline: "Empowering parents with expert-tested baby product insights"
  },

  // Homepage hero section
  hero: {
    title: "Welcome to Tiny Tested",
    subtitle: "Empowering parents with expert-tested baby product insights"
  },

  // Default author information
  author: {
    name: "Tiny Tested Team",
    bio: "TinyTrend Insights delivers expert-driven, meticulously tested reviews and comparisons of essential baby products to empower informed parenting cho...",
    role: "Content Creator",
    image: "/logo.jpg"
  },

  // Section headings throughout the site
  sections: {
    topArticles: {
      title: "Featured Articles",
      description: "Handpicked posts just for you"
    },
    recentPosts: {
      title: "Latest Posts"
    },
    categories: {
      title: "Explore Baby Product Reviews and Recommendations Topics"
    }
  },

  // Newsletter subscription section
  newsletter: {
    title: "Stay Updated",
    description: "Get the latest from Tiny Tested delivered to your inbox",
    disclaimer: "Unsubscribe anytime. We respect your privacy."
  },

  // Blog categories (from brand database)
  categories: [
    { 
      name: "Disposable Diapers",
      icon: "FileText",
      slug: "disposable-diapers"
    },
    { 
      name: "Breast Pumps",
      icon: "FileText",
      slug: "breast-pumps"
    },
    { 
      name: "Convertible Car Seats",
      icon: "FileText",
      slug: "convertible-car-seats"
    },
    { 
      name: "Full-Size Strollers",
      icon: "FileText",
      slug: "full-size-strollers"
    },
    { 
      name: "Strollers & Carriers",
      icon: "FileText",
      slug: "strollers--carriers"
    },
    { 
      name: "Jogging Strollers",
      icon: "FileText",
      slug: "jogging-strollers"
    }
  ],

  // All authors for this brand (with AI-generated portraits)
  authors: [
    {
      id: "8488661a-68e6-4583-be18-cc82bb2e55a2",
      name: "Sophia Nguyen",
      bio: "Sophia writes with a passionate and engaging style, focusing on sustainability and eco-friendliness in baby products. Her background in environmental science and experience as a green living consultant enable her to provide unique insights into eco-friendly parenting choices. Her voice is lively and inspirational, empowering parents to make environmentally responsible decisions without compromising on quality and safety.",
      image: "/authors/8488661a-68e6-4583-be18-cc82bb2e55a2.jpg",
      role: "Eco-Conscious Parenting Advocate"
    },
    {
      id: "e271641f-dc4b-4654-b7be-dbfa373b73db",
      name: "James Mitchell",
      bio: "James brings a meticulous and analytical approach to his writing, offering detailed comparisons and insights backed by data-driven research. With a PhD in Child Development, his expertise lies in understanding how products impact a child's growth and learning. His voice is informative and precise, perfect for parents who appreciate an evidence-based perspective when selecting products for their children.",
      image: "/authors/e271641f-dc4b-4654-b7be-dbfa373b73db.jpg",
      role: "Child Development Expert and Product Analyst"
    },
    {
      id: "8a9552c0-e035-4125-8fdc-4037ff417c66",
      name: "Emma Carter",
      bio: "Emma is known for her warm and approachable writing style, making complex product details accessible to new parents. With a background in pediatric care and product safety certification, she combines her expertise with a motherly touch, focusing on safety and practicality in her reviews. Her voice is reassuring and authoritative, ideal for parents navigating the overwhelming world of baby products.",
      image: "/authors/8a9552c0-e035-4125-8fdc-4037ff417c66.jpg",
      role: "Certified Pediatric Product Specialist"
    }
  ]
}

/**
 * Color configuration
 * Brand colors in oklch() format for consistent rendering
 * Auto-converted from brand hex colors
 */
export const colorContent: ColorConfigSchema = {
  // Light mode colors
  light: {
    primary: "#2563EB",      // #2563EB
    secondary: "#64748B",  // #64748B
    accent: "#F59E0B"         // #F59E0B
  },

  // Dark mode colors (auto-lightened for contrast)
  dark: {
    primary: "#2563EB",
    secondary: "#64748B",
    accent: "#F59E0B"
  }
}
